spring:
  application:
    name: cardian
  # jpa setting
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      format-sql: true
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: true

  # datasource setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/cardian?serverTimezone=UTC
    url: jdbc:mysql://172.17.0.7:3306/cardian?serverTimezone=UTC
    username: a803
    password: a803
